using static Skeleton;

public enum BoneName
{
  None,
  b_l_wrist,
  b_l_forearm_stub,
  b_l_humerus,
  b_l_shoulder,
  b_l_shoulder_end,
  b_l_index1,
  b_l_index2,
  b_l_index3,
  b_l_index_null,
  b_l_index_null_end,
  l_index_finger_pad_marker,
  l_index_finger_tip_marker,
  l_index_fingernail_marker,
  l_index_dip_fe_axis_marker,
  l_index_pip_fe_axis_marker,
  b_l_middle1,
  b_l_middle2,
  b_l_middle3,
  b_l_middle_null,
  b_l_middle_null_end,
  l_middle_finger_pad_marker,
  l_middle_finger_tip_marker,
  l_middle_fingernail_marker,
  l_middle_dip_fe_axis_marker,
  l_middle_knuckle_marker,
  l_middle_pip_fe_axis_marker,
  b_l_pinky0,
  b_l_pinky1,
  b_l_pinky2,
  b_l_pinky3,
  b_l_pinky_null,
  b_l_pinky_null_end,
  l_pinky_finger_pad_marker,
  l_pinky_finger_tip_marker,
  l_pinky_fingernail_marker,
  l_pinky_dip_fe_axis_marker,
  l_pinky_pip_fe_axis_marker,
  b_l_ring1,
  b_l_ring2,
  b_l_ring3,
  b_l_ring_null,
  b_l_ring_null_end,
  l_ring_finger_pad_marker,
  l_ring_finger_tip_marker,
  l_ring_fingernail_marker,
  l_ring_dip_fe_axis_marker,
  l_ring_pip_fe_axis_marker,
  b_l_thumb0,
  b_l_thumb1,
  b_l_thumb2,
  b_l_thumb3,
  b_l_thumb_null,
  b_l_thumb_null_end,
  l_thumb_finger_pad_marker,
  l_thumb_finger_tip_marker,
  l_thumb_fingernail_marker,
  l_thumb_ip_fe_axis_marker,
  l_thumb_knuckle_marker,
  l_thumb_mcp_fe_axis_marker,
  l_thumb_palm_knuckle_marker,
  l_index_knuckle_marker,
  l_index_mcp_aa_axis_marker,
  l_index_mcp_fe_axis_marker,
  l_index_palm_collider_base0_marker,
  l_index_palm_collider_base1_marker,
  l_index_palm_knuckle_marker,
  l_middle_mcp_aa_axis_marker,
  l_middle_mcp_fe_axis_marker,
  l_middle_palm_collider_base0_marker,
  l_middle_palm_collider_base1_marker,
  l_middle_palm_knuckle_marker,
  l_palm_center_marker,
  l_pinky_knuckle_marker,
  l_pinky_mcp_aa_axis_marker,
  l_pinky_mcp_fe_axis_marker,
  l_pinky_palm_collider_base0_marker,
  l_pinky_palm_collider_base1_marker,
  l_pinky_palm_knuckle_marker,
  l_ring_knuckle_marker,
  l_ring_mcp_aa_axis_marker,
  l_ring_mcp_fe_axis_marker,
  l_ring_palm_collider_base0_marker,
  l_ring_palm_collider_base1_marker,
  l_ring_palm_knuckle_marker,
  l_thumb_cmc_aa_axis_marker,
  l_thumb_cmc_fe_axis_marker,
  b_r_wrist,
  b_r_forearm_stub,
  b_r_humerus,
  b_r_shoulder,
  b_r_shoulder_end,
  b_r_index1,
  b_r_index2,
  b_r_index3,
  b_r_index_null,
  b_r_index_null_end,
  r_index_finger_pad_marker,
  r_index_finger_tip_marker,
  r_index_fingernail_marker,
  r_index_dip_fe_axis_marker,
  r_index_pip_fe_axis_marker,
  b_r_middle1,
  b_r_middle2,
  b_r_middle3,
  b_r_middle_null,
  b_r_middle_null_end,
  r_middle_finger_pad_marker,
  r_middle_finger_tip_marker,
  r_middle_fingernail_marker,
  r_middle_dip_fe_axis_marker,
  r_middle_knuckle_marker,
  r_middle_pip_fe_axis_marker,
  b_r_pinky0,
  b_r_pinky1,
  b_r_pinky2,
  b_r_pinky3,
  b_r_pinky_null,
  b_r_pinky_null_end,
  r_pinky_finger_pad_marker,
  r_pinky_finger_tip_marker,
  r_pinky_fingernail_marker,
  r_pinky_dip_fe_axis_marker,
  r_pinky_pip_fe_axis_marker,
  b_r_ring1,
  b_r_ring2,
  b_r_ring3,
  b_r_ring_null,
  b_r_ring_null_end,
  r_ring_finger_pad_marker,
  r_ring_finger_tip_marker,
  r_ring_fingernail_marker,
  r_ring_dip_fe_axis_marker,
  r_ring_pip_fe_axis_marker,
  b_r_thumb0,
  b_r_thumb1,
  b_r_thumb2,
  b_r_thumb3,
  b_r_thumb_null,
  b_r_thumb_null_end,
  r_thumb_finger_pad_marker,
  r_thumb_finger_tip_marker,
  r_thumb_fingernail_marker,
  r_thumb_ip_fe_axis_marker,
  r_thumb_knuckle_marker,
  r_thumb_mcp_fe_axis_marker,
  r_thumb_palm_knuckle_marker,
  r_index_knuckle_marker,
  r_index_mcp_aa_axis_marker,
  r_index_mcp_fe_axis_marker,
  r_index_palm_collider_base0_marker,
  r_index_palm_collider_base1_marker,
  r_index_palm_knuckle_marker,
  r_middle_mcp_aa_axis_marker,
  r_middle_mcp_fe_axis_marker,
  r_middle_palm_collider_base0_marker,
  r_middle_palm_collider_base1_marker,
  r_middle_palm_knuckle_marker,
  r_palm_center_marker,
  r_pinky_knuckle_marker,
  r_pinky_mcp_aa_axis_marker,
  r_pinky_mcp_fe_axis_marker,
  r_pinky_palm_collider_base0_marker,
  r_pinky_palm_collider_base1_marker,
  r_pinky_palm_knuckle_marker,
  r_ring_knuckle_marker,
  r_ring_mcp_aa_axis_marker,
  r_ring_mcp_fe_axis_marker,
  r_ring_palm_collider_base0_marker,
  r_ring_palm_collider_base1_marker,
  r_ring_palm_knuckle_marker,
  r_thumb_cmc_aa_axis_marker,
  r_thumb_cmc_fe_axis_marker,
}

public class BoneNameToBoneId
{
  public static BoneId getBoneId(string boneName)
  {
    var result = boneName switch
    {
      "b_l_wrist" => 0,
      "b_l_forearm_stub" => 1,
      "b_l_thumb0" => 2,
      "b_l_thumb1" => 3,
      "b_l_thumb2" => 4,
      "b_l_thumb3" => 5,
      "b_l_index1" => 6,
      "b_l_index2" => 7,
      "b_l_index3" => 8,
      "b_l_middle1" => 9,
      "b_l_middle2" => 10,
      "b_l_middle3" => 11,
      "b_l_ring1" => 12,
      "b_l_ring2" => 13,
      "b_l_ring3" => 14,
      "b_l_pinky0" => 15,
      "b_l_pinky1" => 16,
      "b_l_pinky2" => 17,
      "b_l_pinky3" => 18,
      "l_thumb_finger_tip_marker" => 19,
      "l_index_finger_tip_marker" => 20,
      "l_middle_finger_tip_marker" => 21,
      "l_ring_finger_tip_marker" => 22,
      "l_pinky_finger_tip_marker" => 23,
      _ => throw new System.Exception($"Invalid boneName: {boneName}"),
    };

    return (BoneId)result;
  }
}